name: shop_application
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.1

  cupertino_icons: ^1.0.8
  dotted_line: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.9.0

  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.8
 
  
  
dev_dependencies:
  
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  

flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500

    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf
          weight: 700


    - family: dana
      fonts:
        - asset: assets/fonts/dana.ttf
          weight: 500
